### ISSUE TITLE
AttributeError: 'list' object has no attribute 'visualize_frames' (notebooks/01_get_started/introduction_to_soccertrack.ipynb)

### ISSUE THREAD

**Issue by pushkin-dev** [AtomScott/SoccerTrack#103]
### Search before asking

- [X] I have searched the SoccerTrack [issues](https://github.com/AtomScott/SoccerTrack/issues) and found no similar bug report.

### Bug

last code section (all the rest passed successfully):
```
save_path = "assets/tracking_results.mp4"
res.visualize_frames(cam.video_path, save_path)
```

out:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [13], line 2
      1 save_path = "assets/tracking_results.mp4"
----> 2 res.visualize_frames(cam.video_path, save_path)

AttributeError: 'list' object has no attribute 'visualize_frames'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AtomScott** [comment]
Hi, sorry for the delay. The reason for this error is that I made a mistake in the `tracker.track` function. The `track` function should return a `BoundingBoxDataFrame` instead of the list it currently does.

For now, please use the following code to correctly save the results:

```python
import soccertrack as st
from soccertrack import Camera
from soccertrack.utils import get_git_root
from soccertrack.mot import SORTTracker
from soccertrack.motion_model import KalmanFilterMotionModel

root = get_git_root()
cam = Camera(path_to_mp4)

inference_config = {'imgsz': 1280}
det_model = st.detection_model.load('yolov8x', inference_config=inference_config)

motion_model = KalmanFilterMotionModel(dt=1/30, process_noise=10000, measurement_noise=10)

tracker = SORTTracker(detection_model=det_model, motion_model=motion_model, metric_gate=0.9, t_lost=20)
tracker.track(cam[:100])
res = tracker.to_bbdf()

save_path = "assets/tracking_results.mp4"
res.visualize_frames(cam.video_path, save_path)
```

Please try this code and let me know if it solves your problem.

**Comment by pushkin-dev** [comment]
thanks, it's solved my problem.
