### ISSUE TITLE
[Feature] Evaluation for common MOT metrics

### ISSUE THREAD

**Issue by AtomScott** [AtomScott/SoccerTrack#13]
### Search before asking

- [ ] I have searched the SoccerTrack [issues](https://github.com/AtomScott/SoccerTrack/issues) and found no similar feature requests.

### Additional

* Python lib for evaluation mot metrics - https://github.com/cheind/py-motmetrics
* Evaluation for MOT methods - https://github.com/cheind/py-motmetrics/blob/develop/motmetrics/apps/eval_motchallenge.py

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!
---
_If you are willing to submit a PR, please do the following._

- [ ] I have discussed the requested feature's details with core devs.
- [ ] I have made a Pull Request (or draft PR).
- [ ] I have linked the PR to this issue.

**Comment by IkumaUchida** [comment]
### 実装方針
* 実装の概要
トラッキング用評価用スクリプトを参考とし、soccertrackの物体検出/モジュールから出力されたcamera detaframeを使用し、物体検出の精度を算出するための仕組みを作成する。

参考コードは以下の通り
[py-motmetrics](https://github.com/cheind/py-motmetrics)

1. camera dataframeを作成
- camera dataframeは以下の構成とする。
    - level 1 - teamid 
    - level 2 - playerid 
    - level 3
        - px - ピッチ座標 X 
        - py - ピッチ座標 Y      
        - bbox_x1 
        - bbox_x2 
        - bbox_y1 
        - bbox_y2 

**現段階のデータセットに関する不明点**
- [ ]  推論時にidが増えてしまう場合のデータセット形について
