### ISSUE TITLE
Error when import podm library

### ISSUE THREAD

**Issue by mcjeong95** [AtomScott/SoccerTrack#25]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/AtomScott/SoccerTrack/issues) and [discussions](https://github.com/AtomScott/SoccerTrack/discussions) and found no similar questions.

### Question

Hi, I cloned this repo and tried to follow your tutorial notebook(`detect_and_track.ipynb`) in `develop` branch.

However, I faced an error as below, so I installed `podm` package but it still occurs.

<img width="767" alt="Screen Shot 2022-08-30 at 8 15 53 PM" src="https://user-images.githubusercontent.com/83578111/187422995-7459d43b-4539-4bc8-a0b5-bbde05ca167c.png">

How should I fix this error?

Thanks.

**Comment by AtomScott** [comment]
Some of the code may not be up to date, let me look into this💪

**Comment by mcjeong95** [comment]
Thanks for your quick reply!

I'll be waiting for the update. 💪
